config/routes.rb
Todo::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "home/index"
  
  resources :list_items do
    member do 
      get :done
      get :set_deadline
      get :start
      get :timer_start
      get :timer_stop
    end
  end

  resources :lists

  devise_for :users
  root 'home#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :list_items, dependent: :destroy
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :list
  has_many :timers, dependent: :destroy

  def elapsed_minutes
    timers.sum("minutes")
  end

  def done!
    update_attribute(:done_at, Time.zone.now)
    timer_stop! if timer_started?
  end

  def expired?
    if deadline_at
      deadline_at < Time.zone.now.beginning_of_day
    else
      false
    end
  end

  def coming?
    if deadline_at
      deadline_at > Time.zone.now.end_of_day
    else
      false
    end
  end

  def timer_start!
    update_attribute(:timer_started_at, Time.zone.now)
  end

  def timer_stop!
    elapsed_minutes = (Time.zone.now - timer_started_at)/60
    timers.create!(started_at: timer_started_at, minutes: elapsed_minutes)
    update_attribute(:timer_started_at, nil)
  end

  def timer_started?
    !timer_started_at.nil?
  end

  def deadline_set?
    !deadline_at.nil?
  end

  def expiring_today?
    deadline_at.to_date == Date.current.to_date
  end

  def start!
    update_attribute(:started_at, Time.zone.now)
    timer_start!
  end

  def started?
    !started_at.nil?
  end

  def self.deadline_set
    where("deadline_at is not null")
  end

  def self.expiring
    where("deadline_at <= :today", today: Time.zone.now.end_of_day)
  end

  def self.not_expired
    where("deadline_at > :today", today: Time.zone.now.end_of_day)
  end

  def self.order_by_list
    order("list_id")
  end

  def self.not_done
    where("done_at is null")
  end

  def self.done
    where("done_at is not null")
  end

  def self.not_started
    where("started_at is null")
  end

  def self.order_by_deadline
    order("deadline_at desc")
  end

  def self.order_by_created_at
    order("created_at desc")
  end

  def self.started
    where("started_at is not null")
  end
end

app/models/timer.rb
class Timer < ActiveRecord::Base
  belongs_to :list_item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy

  def list_items
    ListItem.where(list_id: lists)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @today_tasks = current_user.list_items.not_done.expiring.order_by_list
    @ongoing_tasks = current_user.list_items.not_done.started
    @coming_tasks = current_user.list_items.not_started.not_done.not_expired.order_by_deadline
    @lists = current_user.lists
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_filter :authenticate_user!

  def create
    list = List.find(params[:list])
    ListItem.create!(list: list, content: params[:content])

    render partial: "lists/normal", locals: { list: list }
  end

  def timer_start
    list_item = ListItem.find(params[:id])
    list_item.timer_start!
    
    render text: "ok"
  end

  def timer_stop
    list_item = ListItem.find(params[:id])
    list_item.timer_stop!
    
    render text: "ok"    
  end

  def done
    list_item = ListItem.find(params[:id])
    list_item.done!
    list = List.find(list_item.list_id)

    render partial: "lists/normal", locals: { list: list }
  end

  def set_deadline
    list_item = ListItem.find(params[:id])
    list_item.update_attribute(:deadline_at, params[:deadline])
    render text: "ok"
  end

  def start
    list_item = ListItem.find(params[:id])
    list_item.start!
    render text: "ok"
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new create_list_params
    @list.user = current_user

    if @list.valid?
      @list.save
      redirect_to root_path
    else
      render "new"
    end
  end

  private

  def create_list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.haml
.row
  .col-md-12
    .pull-right
      %h1
        %span.glyphicon.glyphicon-calendar
        = Time.zone.now.strftime("%d %B")
.row
  .col-md-12
    = "&nbsp;".html_safe

.row
  .col-md-12
    .my-panel
      %h2 Today

      - ongoing_ids = []
      - deadline_ids = []

      - if @ongoing_tasks.any?
        %h4 Ongoing
        - ongoing_ids = @ongoing_tasks.load.map(&:id)
        - @ongoing_tasks.each do |list_item|
          = render "list_items/full", list_item: list_item

      - if @today_tasks.any?
        %h4 Deadline
        - deadline_ids = @today_tasks.load.map(&:id)
        - @today_tasks.each do |list_item|
          - unless ongoing_ids.include? list_item.id
            = render "list_items/full", list_item: list_item
      
      - if !@today_tasks.any? and !@ongoing_tasks.any?
        .alert.alert-success
          Done :)

      - if @coming_tasks.any?
        %h4 Coming
        - @coming_tasks.each do |list_item|
          = render "list_items/full", list_item: list_item

.row
  .col-md-12
    .my-panel
      .row
        .col-md-10
          %h2 Lists
        .col-md-2
          .pull-right
            = link_to "<span class='glyphicon glyphicon-plus'></span> New list".html_safe, new_list_path, class:"btn btn-default btn-xs"

      .row
        - if @lists.any?
          - item_per_col = (@lists.count / 3.0).ceil
          - list_array = @lists.load.to_a

          - (0..3).each do |i|
            .col-md-4
              - offset = i*item_per_col
              - col_number = offset+item_per_col-1

              - list_array[offset..col_number].try(:each) do |list|
                %div{id: "list-#{list.id}", style: ""}
                  = render "lists/normal", list: list
        - else
          .col-md-12
            .text-muted
              No list found!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lists</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/list_items/_full.html.haml
%div{class: "top-list-item-#{list_item.id}", style: "padding-bottom:10px;"}
  .label.label-default{class: "label-#{list_item.list.color}"}
    = list_item.list.title
  
  = "&nbsp;".html_safe

  - if list_item.started?
    %div{ class: "btn btn-default btn-xs timer-start-button timer-start-#{list_item.id} ", data: {item_id: list_item.id}, style: "display: #{list_item.timer_started? ? 'none': ''}"}
      %span.glyphicon.glyphicon-play-circle 
      Timer

    %div{ class: "btn btn-danger btn-xs timer-stop-button timer-stop-#{list_item.id} ", data: {item_id: list_item.id}, style: "display: #{list_item.timer_started? ? '': 'none'}" }
      %span.glyphicon.glyphicon-pause 
      Timer


    %div{ class: "btn btn-default btn-xs task-done-button", data: {item_id: list_item.id, list_id: list_item.list.id} }
      %span.glyphicon.glyphicon-ok 
      Done

  - else
    %div{ class: "btn btn-default btn-xs start-button ", data: {item_id: list_item.id} }
      %span.glyphicon.glyphicon-play 
      Work

  - if list_item.expired?
    %span.text-danger
      %strong
        = " #{time_ago_in_words(list_item.deadline_at)} ago"
    %span.text-muted
      = list_item.content

  - elsif list_item.coming?
    %strong
      = " #{time_ago_in_words(list_item.deadline_at)} "
    %span.text-muted
      = list_item.content

  - else
    = list_item.content

app/views/lists/_normal.html.haml
.panel.panel-default
  .panel-heading
    .label.label-default.new-task-button{class: "label-#{list.color}", data: {list_id: list.id}, style: "cursor:pointer;"}
      %span.glyphicon.glyphicon-plus

    = "&nbsp;".html_safe + link_to(list.title, list_path(list), style: "color: black;")
  .panel-body
    .my-list
      %ul.my-ul
        %li.my-li
          .new-task-form{id: "new_task_form_#{list.id}", style: "display: none;"}
            .form-group
              = text_field_tag "content", "", class: "form-control", id: "new_task_content_#{list.id}", placeholder: "Task content"
            .form-group
              = button_tag "save", data: {list_id: list.id}, class: "new-task-submit-button btn btn-success btn-block"

        - list.list_items.order_by_created_at.not_done.each do |item|
          %li.my-li
            .btn-group
              %button.btn.btn-xs.btn-default.dropdown-toggle{data:{toggle:"dropdown"}}
                %span.glyphicon.glyphicon-th-list
                %span.caret
              %ul.dropdown-menu{data: {role: "menu"}}
                %li
                  - deadline_text = "<span class='glyphicon glyphicon-time'></span> Deadline".html_safe
                  = link_to deadline_text, "#", class: "deadline-button", data: {list_id: list.id, item_id: item.id}
                %li
                  - start_text = "<span class='glyphicon glyphicon-play'></span> Start".html_safe
                  = link_to start_text, "#", class: "start-button", data: {list_id: list.id, item_id: item.id}

                %li
                  - done_text = "<span class='glyphicon glyphicon-ok'></span> Done".html_safe
                  = link_to done_text, "#", data: {list_id: list.id, item_id: item.id}, class: "task-done-button"
            %div{id: "list_item_deadline_#{item.id}", style: "margin-top: 5px; display:none;"}
              .panel.panel-default
                .panel-body
                  = text_field_tag "deadline", item.deadline_at.to_s[0..9], class: "textarea form-control datepicker", style: "width: 150px; float: left; margin-right: 10px;"
                  = button_tag "save", data: {item_id: item.id}, class: "task-deadline-submit-button btn btn-success"
            - if item.deadline_set?
              - if item.expiring_today?
                %span.badge= "today"
              - elsif !item.expired?
                %span.badge{style: "background-color:#9DE0FF;color:#0F6698;"}= distance_of_time_in_words_to_now(item.deadline_at)
              - else
                %span.badge{style: "background-color:#E64E3A;"}= "#{distance_of_time_in_words_to_now(item.deadline_at)} ago"

            = item.content

app/views/lists/new.html.haml
.row
  .col-md-12
    &nbsp;

.row
  .col-md-12
    .panel.panel-default
      .panel-body
        %h2 New list

        %div{style: "width: 400px;"}
          = simple_form_for(@list, html: {role: "form" }) do |f|
            .form-group
              = f.input :title, input_html: {class: "form-control"}

            .form-group
              = f.button :submit, class: "btn btn-success"

app/views/lists/show.html.haml
.row
  .col-md-12
    %h1= @list.title

.row
  .col-md-12
    .panel.panel-default
      .panel-body

        - @list.list_items.done.order("done_at desc").each do |item|
          %h4= item.content
          
          %span.glyphicon.glyphicon-calendar
          =item.done_at.strftime("%b %d")
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          %span.glyphicon.glyphicon-time
          =item.elapsed_minutes
          = " min"
          %hr